version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: coloqueasenha
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: coloqueasenha
    links:
      - mongo
    networks:
      - rede-mongo-docker
      
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: coloqueasenha
    ports:
      - "27017:27017"
    volumes:
      - /cdh/containers/mongodb:/data/db
    networks:
      - rede-mongo-docker

networks: 
    rede-mongo-docker:
      driver: bridge
